// tslint:disable
/* eslint-disable */
/**
 * 账户开放接口
 * V1.0.0版本
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DefaultApi, } from './../api'
import { DefaultApiFetchParamCreator, } from './../api'
import { Configuration } from "../configuration";
import { AxiosInstance } from "axios";


interface DefaultApiType {
  api: DefaultApi;
  params: ReturnType<typeof DefaultApiFetchParamCreator>;
  config: Configuration;
}


interface ServiceApiGroupType {
  DefaultApi: DefaultApiType;
  
}

export const buildApi = (
  basePath: string,
  axios: AxiosInstance
): ServiceApiGroupType => {
  const configuration = new Configuration({ basePath });
  return {
    DefaultApi: {
      api: new DefaultApi(configuration, basePath, axios),
      params: DefaultApiFetchParamCreator(configuration),
      config: configuration,
    },
    
  };
};
